### ISSUE TITLE
npm ERR! notarget No matching version found for @rhino.fi/dvf-utils@1.4.11.

### ISSUE THREAD

**Issue by tuncatunc** [DeversiFi/dvf-client-js#559]
Hi,

When trying to install `@rhino.fi/client-js` i got this error.
The latest version of https://www.npmjs.com/package/@rhino.fi/dvf-utils is 1.4.9.
@rhino.fi/client-js requires 1.4.11.

<img width="786" alt="image" src="https://github.com/rhinofi/client-js/assets/6542344/f4246bae-4e2a-4f1f-85c2-dcf1824befb6">

**Comment by aleksa95** [comment]
Hello,

That repository has been deprecated.
Here is the message from the README:

"This open-source client will be deprecated in December 2023. If you use this client to interact with rhino.fi for any reason please join our Discord and let us know so that we can continue to ensure you are supported https://discord.com/invite/V93Bxn7hAY or email [support@rhino.fi](mailto:support@rhino.fi)"

**Comment by tuncatunc** [comment]
If it’s deprecated what should I use instead?

**Comment by aleksa95** [comment]
Please let us know via email (or in this thread) how you have used the client so far and we will try to help you
Be as specific as you can, this will be helpful and we will be able to provide an answer sooner

**Comment by tuncatunc** [comment]
I haven’t developed an dapp using client-js.
If there’s alternatives I would like to know

**Comment by adrian-gierakowski** [comment]
we've now published the missing package

please keep in mind that even though this library should work as is, we are not planning to release any updates to it going forward

**Comment by tuncatunc** [comment]
Thank you @adrian-gierakowski 
This will make my project possible to exists.
