### ISSUE TITLE
17.fullWithdrawalRequest doesn't return funds to wallet.

### ISSUE THREAD

**Issue by CatScan-crypt** [DeversiFi/dvf-client-js#90]
using test net, and after a several attempts i get same result-
getting a Txn only for billing my account for that withdrawal but funds never return to my wallet.

example :
node dvf-client-js-master\examples\17.fullWithdrawalRequest.js

Full withdrawal request response -> { transactionHash:
   '0x2c0f6c938dca662179f76fdf9697030be722f17bcce10c7b2105bcc08a87909e' }

Stopping provider...

is this only test net issue or something else?

**Comment by plutoegg** [comment]
Full withdrawal is only supposed to be used in emergencies (like if DeversiFi tries to sensor you by refusing to honour your withdrawal request using the regular withdrawal API).

There is an additional cost associated with it because of that. However you should still eventually see the withdrawal get processed by us. I believe testnet batches might have been delayed due to our address on-chain not having enough Ropsten ETH to submit the proofs.

I've just fixed that so it should all start appearing in the next 15 minutes

**Comment by AliMeer** [comment]
If the intention was to withdraw, then `dvf.withdraw` not `fullwithdraw`.
After that there is a wait time to wait for the next starkware batch to be created, about 10 - 20 min on ropsten testnet.
During the wait time the status of the withdraw can be checked by calling `dvf.getWithdrawals` and once a withdrawal is ready it can be transferred to the wallet by calling `dvf.withdrawOnChain`

**Comment by CatScan-crypt** [comment]
thanks @plutoegg  @AliMeer 

i wanted just to test the example as an emergency,
didn't see any docs about it and wanted to understand if this will cost a withdrawal transfer fee for every token that will be your the account and withdraw every one of them. 
 or 
it will liquefy all tokens in the account to the parameter that is in /src/fullWithdrawalRequest and only than it will transfer one token back to the wallet.

tested it now and i can see there is some problem with your the account-

 Contract 0x5783323064dda4a1ebe62deffef46750bd2c560c 
 Warning! Error encountered during contract execution [Reverted] 

this goes to most of incoming transactions to this contract, weird but my transaction seems to get approved.


BTW after this resolved can i add your instruction you mentioned above,
as a content to README.md?

**Comment by CatScan-crypt** [comment]
Works perfect now 🐱‍🏍

waiting on your call about adding this as a content  🙏
